.* Generated by VyperHelp on 06/23/23.
:userdoc.
:docprof toc=123456.
:title..* Subject&colon. 
.* Subject: 
.* Version: 
.* Copyright: 
.* Author: 
:h1 res=3100 id='PANEL_PRODUCTINFO'.
Product information dialog
:p.This dialog displays information about the application&comma. such     as
version number and copyright notice&per. 
:h2 res=3110 id='PANEL_PRODUCTINFO_OK'.
OK
:p.The OK button closes the Product information dialog&per. 
:euserdoc.
